languages = \
{
	"english": {
		"self": "english",
		"": "",
		"Last Name": "Last Name",
		"First Name": "First Name",
		"Chinese Name": "Chinese Name",
		"School Location": "School Location",
		"Barcode": "Barcode",
		"Date of Birth": "Date of Birth",
		"Age": "Age",
		"Parent Name": "Parent Name",
		"Home Phone": "Home Phone",
		"Cell Phone": "Cell Phone",
		"Cell Phone 2": "Cell Phone 2",
		"Pick up Person": "Pick up Person",
		"Address": "Address",
		"State": "State",
		"City": "City",
		"Zipcode": "Zipcode",
		"Weekday/Weekend": "Weekday/Weekend",
		"Tuition Paid Day": "Tuition Paid Day",
		"Payment Method": "Payment Method",
		"Tuition Pay Amount": "Total Amount",
		"E-mail": "E-mail",
		"Service Type": "Service Type",
		"Classes Awarded": "Classes Awarded",
		"Classes Remaining": "Classes Remaining",
		"Date": "Date",
		"Check-In Time": "Check-In Time",
		"Check-Out Time": "Check-Out Time",
		"Class Time": "Class Time",
		"How did you hear about the school?": "How did you hear\nabout this school?",
		"Notes": "Notes",
		"No teacher": "\nTeacher was not found!\nType in the correct name or\ncontact your system administrator.",
		"Con teacher": "\nAre you sure you would like\nto add this to the Database?",
		"Con S teacher": "\nAre you sure you would like\nto save this teacher's information to the Database?",
		"Ase teacher": "\nTeacher with this barcode exists in the database\nAdding this teacher will overwrite the existing teacher.\nOverwrite current teacher?",
		"Sa teacher": "\nTeacher has been added to the database.",
		"Cs teacher": "\nCheck in the teacher?",
		"Check out prompt": "\nCheck out the teacher?",
		"No classes": "\Teacher does not have any more classes!",
		"Con print": "\nYou sure to print file?",
		"Overwrite Checkout": "\nTeacher checked-out today.\nOverwrite current check-out?",
		"No Check-in today": "\nTeacher has not checked-in today",
		"Confirm late check-in": "\nDo you want to count this Check-In as 9:15AM?",
		"ok": "    Ok    ",
		"yes": "    Yes    ",
		"no": "    No    ",
		"impdb": "Import Database",
		"expdb": "Export Database",
		"impxls": "Import from Excel",
		"impt": "Import Time Data",
		"imptxls": "Import Time Data from Excel",
		"expxls": "Export to Excel",
		"curfile": "Current Database File",
		"browse": "Browse",
		"browsephoto": "Select Picture",
		"filepath": "File Path",
		"Back": "Back",
		"Next": "Next",
		"saveto": "Save To",
		"Save": "Save",
		"choosedb": "Choose Database",
		"Change Language": "中文显示",
		"awardclass": "Award Classes",
		"awardoneclass": "Single (+1)",
		"awardaddclass": "Award Additional Classes",
		"addteacher": "Add Teacher to Database",
		"Add Teachers": "Add Teachers", #teachers* for buttons
		"Check-in Teacher": "Check-in Teacher",
		"Check-out Teacher": "Check-Out Teacher",
		"Teacher Database": "Teacher Database",
		"Tools": "Database Management",
		"Back to Main Menu": "Back to Main Menu",
		"Exit": "Exit",
		"Search": "Search",
		"cinteacher": "Check-In Teacher",
		"Search By": "Search By",
		"saveteacher": "Save Teacher to Database",
		"Database succesfully updated!": "Database succesfully updated!",
		"File could not be imported": "File could not be imported",
		"Cancel": "Cancel",
		"Please choose a file": "\nPlease choose a file",
		"spec": "",
		"Classes remaining for this teacher": "Classes remaining for this teacher",
		"gold60": "Gold (+60)",
		"basic15": "Basic (+15)",
		"Ret to Main": "Return to main window without saving?",
		"Scan": "Scan",
		"Manual": "Manual",
		"close": "Close",
		"Amount Owed": "Amount Owed",
		">> Next 30 >>": "Next",
		"<< Previous 30 <<": "Previous",
		">>> Last Page >>>": "Last Page",
		"Import succesful": "Import succesful",
		"Teachers imported: ": "Teacher imported: ",
		"Attendance data imported: ": "Attendance imported: ",
		"Teacher information": "Teacher information",
		"Address information": "Address",
		"Contact information": "Contact",
		"Payment information": "Payment",
		"Class time": "Class time",
		"Renew classes": "Renew classes",
		"Number of classes": "Classes to add",
		"Membership Expired": "Membership Expired",
		"Card Printed": "Card Printed",
		"Already Paid": "Already Paid",
		"Phone Number": "Phone Number",
		"RYB Teacher Management" : "RYB Teacher Management",
		"Print Report": "Print Report",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"salrep": "Salary Report",
		"print to file": "Make Report",
		"today's date": "Today's date",
		"Last Payment": "Last Payment",
		"dollar per hour": "Dollars per hour",
		"Hour": "Hour",
		"Minute": "Minute",
		"AM/PM": "AM/PM",
		"Print All": "Print All",
		"Confirm Time": "Confirm Time",
		"Confirm": "Confirm",
		"10s": " 10s",
		"20s": " 20s",
		"50s": " 50s",
		"100s": " 100s",
		"set": "Set",
		"reset": "Reset",
		"resetcheckin": "Reset Check-In",
		},

	"chinese": {
		"self": "chinese",
		"First Name": "    名    ",
		"Last Name": "    姓    ",
		"Chinese Name": "  中文名字  ",
		"School Location": "学校位置",
		"Barcode": "条码号",
		"Old Teacher ID": "旧学号",
		"Date of Birth": "生日",
		"Age": "年龄",
		"Gender": "性别",
		"Parent Name": "家长姓名",
		"Home Phone": "家庭电话",
		"Cell Phone": "手机",
		"Cell Phone 2": "手机 2",
		"Pick up Person": "学生接人",
		"Address": "住址",
		"State": "州",
		"City": "城市",
		"Zipcode": "邮政编码",
		"Weekday/Weekend": "平日/周末",
		"Tuition Paid Day": "支付学费日期",
		"Payment Method": "付款方式",
		"Tuition Pay Amount": "总学费金额",
		"E-mail": "电子邮件",
		"Service Type": "课程级别",
		"Classes Awarded": "学生课程总数",
		"Classes Remaining": "剩下的课程",
		"Date": "日期",
		"Check-In Time": "到达时间",
		"Class Time": "上课时间",
		"How did you hear about the school?": "你是怎么找到我们学校?",
		"Notes": "记录",
		"No teacher": "\n找不到的学生 ！\n键入正确的名称或与系统管理员联系。\n",
		"Con teacher": "\n你确定你想这位老师向数据库中添加?",
		"Ase teacher": "\n一个老师用相同的条码。\n如果想添加这个老师,你要覆盖旧的老师\n",
		"Sa teacher": "\n教师已被添加到数据库中",
		"Cs teacher": "\n入住这个老师?\n",
		"Check out prompt": "\nCheck out the teacher?",
		"No classes": "\n这名学生没有课程",
		"Con print": "\n你想做报告吗？",
		"Overwrite Checkout": "\n教师今天已经签出, 覆写目前签出",
		"No Check-in today": "\nTeacher has not checked-in today",
		"Confirm late check-in": "\nDo you want to count this Check-In as 9:15AM?",
		"ok": "    确认    ",
		"yes": "    确认    ",
		"no": "    拒绝    ",
		"Change Language": "English Language Display",
		"awardclass": "奖类",
		"awardoneclass": "添加一课 (+1)",
		"awardaddclass": "奖其他类",
		"browse": "浏览",
		"browsephoto": "浏览照片",
		"addteacher": "新增学生资料",
		"Add Teachers": "新增教师", #teachers* for buttons
		"Check-in Teacher": "签入出席教师",
		"Check-out Teacher": "签出这个教师",
		"Save": "保存",
		"Teacher Database": "老师资料库",
		"Tools": "数据库管理",
		"Back to Main Menu": "返回到主菜单",
		"Exit": "关闭软件",
		"Next": "下一次",
		"Back": "返回",
		"Search": "搜索学生",
		"Search By": "搜索方式",
		"cinteacher": "入住教师",
		"saveteacher": "储存老师数据库",
		"Database succesfully updated!": "数据库成功更新 ！\n",
		"File could not be imported": "不能导入文件\n",
		"Cancel": "取消",
		"Please choose a file": "\n请选择一个文件",
		"impdb": "导入数据库",
		"expdb": "导出数据库",
		"impxls": "从 Excel 中导入",
		"impt": "导入时间数据",
		"imptxls": "从 Excel 导入时间数据",
		"expxls": "导出到 excel 中",
		"curfile": "当前数据库文件",
		"choosedb": "选择数据库",
		"": "",
		"Classes remaining for this teacher": "学生剩余的课程",
		"spec": "",
		"gold60": "黄金 (+60)",
		"basic15": "基本 (+15)",
		"Ret to Main": "返回到软件而不保存吗？",
		"Scan": "Scan",
		"Manual": "Manual",
		"Con S teacher": "确实要将此学生的信息保存到数据库吗？",
		"close": "关闭",
		"Amount Owed": "所欠学费数额",
		">> Next 30 >>": "下一个",
		"<< Previous 30 <<": "上一页",
		">>> Last Page >>>": "最后一页",
		"Import succesful": "导入成功\n",
		"Teachers imported: ": "导入的学生: ",
		"Attendance data imported: ": "导入考勤: ",
		"Teacher information": "教师信息",
		"Address information": "地址",
		"Contact information": "联络",
		"Payment information": "付款资料",
		"Class time": "上课时间",
		"Renew classes": "添加课程",
		"Membership Expired": "会员已过期",
		"Number of classes": "添加课程",
		"Card Printed": "已打印卡",
		"Already Paid": "已支付学费",
		"Phone Number": "电话号码",
		"RYB Teacher Management" : "红黄蓝学生记录软件",
		"Print Report": "打印报告",
		"sdate": "Search Date",
		"Select Folder": "Select Folder",
		"filepath": "File Path",
		"salrep": "薪资报告",
		"print to file": "做薪水报告",
		"today's date": "Today's date",
		"Last Payment": "Last Payment",
		"dollar per hour": "Dollars per hour",
		"Hour": "Hour",
		"Minute": "Minute",
		"AM/PM": "AM/PM",
		"Print All": "Print All",
		"Confirm Time": "Confirm Time",
		"Confirm": "Confirm",
		"10s": " 10s",
		"20s": " 20s",
		"50s": " 50s",
		"100s": " 100s",
		"set": "Set",
		"reset": "Reset",
		"resetcheckin": "Reset Check-In",
		}
		
}